apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateway.yaml
- certificate.yaml

patches:
- path: private/patch/gateway.yaml
  target:
    kind: Gateway
    name: argocd-gateway
- path: private/patch/certificate.yaml
  target:
    kind: Certificate
    name: argocd