apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- clusterissuer-lets-encrypt.yaml

patches:
- path: private/iam-annotation.yaml
  target:
    kind: ServiceAccount
    name: cert-manager-acme-dns01-route53
- path: private/issuer.yaml
  target:
    kind: ClusterIssuer
